security:
    encoders:
        App\Entity\AdminUser: auto
    providers:
        users_in_db:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_in_db
            guard:
                authenticators:
                    - App\Security\AppUserAuthenticator
            logout:
                path: adminLogout
    access_control:
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
