vich_uploader:
    db_driver: orm

    mappings:
        advertImage:
            uri_prefix: /images/adverts
            upload_destination: '%kernel.project_dir%/public/images/adverts'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
